### ISSUE TITLE
grappelli.dashboard: UnicodeDecodeError when there is utf-8 character in verbose_name_plural in model.Meta

### ISSUE THREAD

**Issue by m-aciek** [sehmaschine/django-grappelli#620]
Python 2.7.9
Django 1.8.2
Django Grappelli tip@stable/2.7.x
Error with traceback:
```
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 1292, in render
    return t.render(new_context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 211, in render
    return self._render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/lib/python2.7/site-packages/django/template/defaulttags.py", line 224, in render
    nodelist.append(node.render(context))
  File "/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/lib/python2.7/site-packages/django/template/base.py", line 1271, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/src/django-grappelli/grappelli/dashboard/templatetags/grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "/src/django-grappelli/grappelli/dashboard/modules.py", line 271, in init_with_context
    items = self._visible_models(context['request'])
  File "/src/django-grappelli/grappelli/dashboard/utils.py", line 139, in _visible_models
    return filter_models(request, included, excluded)
  File "/src/django-grappelli/grappelli/dashboard/utils.py", line 113, in filter_models
    pattern_items.sort(key=lambda x: str(x[0]._meta.verbose_name_plural.encode('utf-8')))
  File "/src/django-grappelli/grappelli/dashboard/utils.py", line 113, in <lambda>
    pattern_items.sort(key=lambda x: str(x[0]._meta.verbose_name_plural.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```
Edit: I found #590, it seems to be the same problem, still not resolved.

**Comment by m-aciek** [comment]
My fault, marking strings as unicode did the work.
```
class Meta:
        verbose_name = u"zamówienie"
        verbose_name_plural = u"zamówienia"
```
