### ISSUE TITLE
Support for Django 1.9

### ISSUE THREAD

**Issue by debnet** [sehmaschine/django-grappelli#678]
```traceback
Traceback (most recent call last):
  File "D:\Git\nouvelleoffre-back\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\core\management\__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\core\management\__init__.py", line 324, in execute
    django.setup()
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "d:\virtualenvs\nouvelleoffre\src\django-grappelli\grappelli\dashboard\__init__.py", line 1, in <module>
    from grappelli.dashboard.dashboards import *
  File "d:\virtualenvs\nouvelleoffre\src\django-grappelli\grappelli\dashboard\dashboards.py", line 14, in <module>
    from grappelli.dashboard import modules
  File "d:\virtualenvs\nouvelleoffre\src\django-grappelli\grappelli\dashboard\modules.py", line 9, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\contrib\contenttypes\models.py", line 159, in <module>
    class ContentType(models.Model):
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\db\models\base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\apps\registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\apps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Django 1.9b1, Python 3.5 and Django Grappelli 2.7.1

Thanks. ;)

**Comment by sehmaschine** [comment]
@debnet FYI: We're dealing with 1.9 once there's an official release. I'm closing this for now since there's probably tons of issues with 1.9.

**Comment by HWDexperte** [comment]
Now, Django 1.9 is a thing and this Error persists. Is the support for Django 1.9 planned?

**Comment by wjakob** [comment]
Agreed -- it would be fantastic to have Django 1.9 support now that it's the stable release.

**Comment by sehmaschine** [comment]
support for 1.9 is definitely planned ... I hope to find some spare time within the next couple of days. sorry for the delay on this issue.
