### ISSUE TITLE
Incompatible with django 1.9

### ISSUE THREAD

**Issue by robslotboom** [sehmaschine/django-grappelli#694]
After upgrading to Django 1.9 the following error is logged when issueing the admin action "delete selected".

# missing attribute
<code>
django.template.base.VariableDoesNotExist: Failed lookup for key [form] in '[\'&#60;td class="action-checkbox"&#62;&#60;input class="action-select" name="_selected_action" type="checkbox" value="49" /&#62;&#60;/td&#62;\', \'&#60;th style="padding-left:5px"&#62;&#60;a href="/admin/cms/page/49/change/"&#62;aanbod&#60;/a&#62;&#60;/th&#62;\', \'&#60;td&#62;aanbod&#60;/td&#62;\', \'&#60;td&#62;Aanbod&#60;/td&#62;\', \'&#60;td&#62;&#60;img src="/static/admin/img/icon-yes.svg" alt="True" /&#62;&#60;/td&#62;\', \'&#60;td&#62;&#60;img src="/static/admin/img/icon-yes.svg" alt="True" /&#62;&#60;/td&#62;\', \'&#60;td class="nowrap"&#62;-&#60;/td&#62;\', \'&#60;td&#62;/aanbod/&#60;/td&#62;\']'
</code>

A minor issue is the deprication warning regarding the the new appname, namespace convention in urls.

Best regards,

Robert Slotboom

**Comment by saulshanabrook** [comment]
Also the `admin/img/icon_deletelink.gif` has been changed to `admin/img/icon_deletelink.svg` in Django 1.9 so am getting this when I run `collectstatic`

```
Post-processing 'grappelli/stylesheets/screen.css' failed!

Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 176, in handle
    collected = self.collect()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 128, in collect
    raise processed
whitenoise.django.MissingFileError: The file 'admin/img/icon_deletelink.gif' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x1e78950>.

The CSS file 'grappelli/stylesheets/screen.css' references a file which could not be found:
  admin/img/icon_deletelink.gif

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```

**Comment by karolyi** [comment]
+1, `django-pipeline` compilation breaks because of this

**Comment by karolyi** [comment]
thx, my good sir.
