### ISSUE TITLE
fix icon_deletelink.gif

### ISSUE THREAD

**Issue by parsch** [sehmaschine/django-grappelli#709]
see #694 

> Also the `admin/img/icon_deletelink.gif` has been changed to `admin/img/icon_deletelink.svg` in Django 1.9 so am getting this when I run `collectstatic`

**Comment by sehmaschine** [comment]
@parsch what exactly do you get? works fine with my setup.

**Comment by michalwerner** [comment]
When I run `python manage.py collectstatic`, I get:

```
Post-processing 'grappelli/stylesheets/screen.css' failed!

Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File ".............../lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File ".............../lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".............../lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".............../lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File ".............../lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 176, in handle
    collected = self.collect()
  File ".............../lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 128, in collect
    raise processed
  File ".............../lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 245, in post_process
    content = pattern.sub(converter, content)
  File ".............../lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 184, in converter
    hashed_url = self.url(unquote(joined_result), force=True)
  File ".............../lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File ".............../lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File ".............../lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'admin/img/icon_deletelink.gif' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x7f1addddecc0>.
```

I use django-pipeline, but I think it doesn't matter. I also noticed that there's no error unless I flush static directory first.

**Comment by sehmaschine** [comment]
@michalwerner I do think it's related to django-pipeline. please try again without that package.

**Comment by michalwerner** [comment]
@sehmaschine, you're right, my bad. Error occurs only when some other package like django-pipeline tries to do something with static files. 
But it does not change the fact that path to that icon changed in Django from: `admin/img/icon_deletelink.gif` to `admin/img/icon-deletelink.svg`.

**Comment by sehmaschine** [comment]
see #714
