### ISSUE TITLE
collectstatic fails with CachedStaticFilesStorage

### ISSUE THREAD

**Issue by nferrari** [sehmaschine/django-grappelli#720]
Hi,

I just deployed a clean and empty Django project, with last grappelli trunk branch (that's all I got in my virtualenv: Django 1.9.1 and grappelli 2.8.1). If I activate the setting below, then the collectstatic command fails.

The setting:

`STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'`

The traceback:
```
Post-processing 'grappelli/stylesheets/screen.css' failed!

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lecentre/.virtualenvs/test/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/lecentre/.virtualenvs/test/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/lecentre/.virtualenvs/test/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/lecentre/.virtualenvs/test/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/lecentre/.virtualenvs/test/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 176, in handle
    collected = self.collect()
  File "/home/lecentre/.virtualenvs/test/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 128, in collect
    raise processed
ValueError: The file 'admin/img/icon_deletelink.gif' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x7f02f1030250>.
```

No problem without this setting. Is there any known issue? Am I missing something?

Thank you.

**Comment by PaoloC68** [comment]
@nferrari my pull request #722 should have fixed this, can you please confirm and close this issues? You should use branch stable/2.8.x

**Comment by nferrari** [comment]
Indeed. Thank you!
