### ISSUE TITLE
ModuleNotFoundError: No module named 'grappellidjango' after install on Django 2.0.5, Python 3.6

### ISSUE THREAD

**Issue by StevenMapes** [sehmaschine/django-grappelli#849]
There is a major bug that makes this project incompatible with Django 2.0.5 and probably all other versions.

To replicate follow the install guide so pip install, update setting.py, update urls.py and then run collectstatic to receive the following exception and backtrace

`ModuleNotFoundError: No module named 'grappellidjango'`

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/steve/venv/ldt/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/steve/venv/ldt/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/steve/venv/ldt/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/steve/venv/ldt/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/steve/venv/ldt/lib/python3.6/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grappellidjango'
```

Tested with Python 3.6 with the following packages installed within the venv

```
Package              Version
-------------------- -------
argon2-cffi          18.1.0 
boto3                1.7.29 
botocore             1.10.29
cffi                 1.11.5 
coverage             4.5.1  
Django               2.0.5  
django-debug-toolbar 1.9.1  
django-grappelli     2.11.1 
django-storages      1.6.6  
docutils             0.14   
jmespath             0.9.3  
mysqlclient          1.3.12 
Pillow               5.1.0  
pip                  10.0.1 
pycparser            2.18   
python-dateutil      2.7.3  
pytz                 2018.4 
s3transfer           0.1.13 
setuptools           39.2.0 
six                  1.11.0 
sqlparse             0.2.4  
```

**Comment by sehmaschine** [comment]
I don't know what you're doing exactly, but that's definitely a bug with your setup. There is no package `grappellidjango` (at least it's not a package needed with grappelli or provided by us).

**Comment by sehmaschine** [comment]
Maybe you forgot a comma between `grappelli` and `django.contrib.xxx` with `INSTALLED_APPS`. Closing this for now (please reopen if you think it's a bug).
