### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by gcd445** [sehmaschine/django-grappelli#851]
Hi , I followed https://django-grappelli.readthedocs.io/en/latest/quickstart.html but I'm getting 
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000002188D6BE8C8>
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "D:\Python36\lib\site-packages\django\core\management\commands\runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "D:\Python36\lib\site-packages\django\core\management\base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "D:\Python36\lib\site-packages\django\core\management\base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "D:\Python36\lib\site-packages\django\core\checks\registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "D:\Python36\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "D:\Python36\lib\site-packages\django\core\checks\urls.py", line 67, in _load_all_namespaces
    namespaces.extend(_load_all_namespaces(pattern, current))
  File "D:\Python36\lib\site-packages\django\core\checks\urls.py", line 67, in _load_all_namespaces
    namespaces.extend(_load_all_namespaces(pattern, current))
  File "D:\Python36\lib\site-packages\django\core\checks\urls.py", line 67, in _load_all_namespaces
    namespaces.extend(_load_all_namespaces(pattern, current))
  [Previous line repeated 984 more times]
  File "D:\Python36\lib\site-packages\django\core\checks\urls.py", line 59, in _load_all_namespaces
    ':'.join(parents + (url.namespace,)) for url in url_patterns
RecursionError: maximum recursion depth exceeded
```

**Comment by sehmaschine** [comment]
That seems to be an error with your setup (e.g. URL patterns), but not related to grappelli. If you think this is because of grappelli, please try to debug and add some information so we're able to reproduce this.
