### ISSUE TITLE
RemovedInDjango41Warning raised in Django 3.2 under pytest-django

### ISSUE THREAD

**Issue by johnthagen** [sehmaschine/django-grappelli#966]
Our test suite runs with the following command:

```bash
$ python -Werror -m pytest
```

It errors due to a deprecation warning triggered by Grappelli:

```
Traceback (most recent call last):
  File "python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".tox/py39/lib/python3.9/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File ".tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File ".tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File ".tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File ".tox/py39/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File ".tox/py39/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File ".tox/py39/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File ".tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File ".tox/py39/lib/python3.9/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File ".tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File ".tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File ".tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File ".tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File ".tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1191, in _preparse
    self.hook.pytest_load_initial_conftests(
  File ".tox/py39/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File ".tox/py39/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File ".tox/py39/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File ".tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File ".tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File ".tox/py39/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File ".tox/py39/lib/python3.9/site-packages/pytest_django/plugin.py", line 348, in pytest_load_initial_conftests
    _setup_django()
  File ".tox/py39/lib/python3.9/site-packages/pytest_django/plugin.py", line 234, in _setup_django
    django.setup()
  File ".tox/py39/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File ".tox/py39/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File ".tox/py39/lib/python3.9/site-packages/django/apps/config.py", line 189, in create
    warnings.warn(message, RemovedInDjango41Warning, stacklevel=2)
django.utils.deprecation.RemovedInDjango41Warning: 'grappelli' defines default_app_config = 'grappelli.apps.GrappelliConfig'. Django now detects this configuration automatically. You can remove default_app_config.
```

Package versions:
- Python 3.9.5
- Django 3.2.3
- pytest-django 4.3.0
- django-grappelli 2.15.1

**Comment by maerteijn** [comment]
Thats is because you invoke your testsuite with `-Werror` which turns all warnings into errors.

**Comment by johnthagen** [comment]
@maerteijn Yes, thanks. I reported hoping that the `RemovedInDjango41Warning` could be fixed/suppressed in `django-grappelli`.

**Comment by ionelmc** [comment]
I have this meanwhile:
```ini
filterwarnings =
    ignore:'grappelli:django.utils.deprecation.RemovedInDjango41Warning::
```

**Comment by johnthagen** [comment]
The format that worked for me was:

```toml
# pyproject.toml
[tool.pytest.ini_options]
filterwarnings = [
    "ignore::django.utils.deprecation.RemovedInDjango41Warning:django",
]
```

**Comment by sehmaschine** [comment]
So you're having a solution to this and the ticket can be closed, right?

**Comment by johnthagen** [comment]
I'm actually not using grapelli any longer, but I think the correct fix (to avoid every user having to suppress the warning) would be someone like: https://github.com/lazybird/django-solo/blob/9fad4443cf7287411fd7a09194fb907a6ae8576a/solo/__init__.py#L8

```
if django.VERSION < (3, 2):
    default_app_config = 'solo.apps.SoloAppConfig'
```
