### ISSUE TITLE
test_autocomplete_lookup and test_m2m_lookup fail on Django 4

### ISSUE THREAD

**Issue by jayvdb** [sehmaschine/django-grappelli#979]
```py
[   64s] ____________________ RelatedTests.test_autocomplete_lookup _____________________
[   64s] 
[   64s] self = <grappelli.tests.test_related.RelatedTests testMethod=test_autocomplete_lookup>
[   64s] 
[   64s]     def test_autocomplete_lookup(self):
[   64s]         """
[   64s]         Test autocomplete lookup
[   64s]         """
[   64s]         self.client.login(username="User001", password="user001")
[   64s] >       response = self.client.get(reverse("grp_related_lookup"))
[   64s] 
[   64s] grappelli/tests/test_related.py:193: 
[   64s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   64s] /usr/lib/python3.9/site-packages/django/test/client.py:747: in get
[   64s]     response = super().get(path, data=data, secure=secure, **extra)
[   64s] /usr/lib/python3.9/site-packages/django/test/client.py:396: in get
[   64s]     return self.generic('GET', path, secure=secure, **{
[   64s] /usr/lib/python3.9/site-packages/django/test/client.py:473: in generic
[   64s]     return self.request(**r)
[   64s] /usr/lib/python3.9/site-packages/django/test/client.py:721: in request
[   64s]     self.check_exception(response)
[   64s] /usr/lib/python3.9/site-packages/django/test/client.py:582: in check_exception
[   64s]     raise exc_value
[   64s] /usr/lib/python3.9/site-packages/django/core/handlers/exception.py:47: in inner
[   64s]     response = get_response(request)
[   64s] /usr/lib/python3.9/site-packages/django/core/handlers/base.py:181: in _get_response
[   64s]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[   64s] /usr/lib/python3.9/site-packages/django/views/generic/base.py:69: in view
[   64s]     return self.dispatch(request, *args, **kwargs)
[   64s] /usr/lib/python3.9/site-packages/django/views/generic/base.py:101: in dispatch
[   64s]     return handler(request, *args, **kwargs)
[   64s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   64s] 
[   64s] request = <grappelli.views.related.RelatedLookup object at 0x7fbbe0f02850>
[   64s] args = (<WSGIRequest: GET '/grappelli/lookup/related/'>,), kwargs = {}
[   64s] 
[   64s]     @wraps(view_func)
[   64s]     def _wrapped_view_func(request, *args, **kwargs):
[   64s]         if not isinstance(request, HttpRequest):
[   64s] >           raise TypeError(
[   64s]                 "never_cache didn't receive an HttpRequest. If you are "
[   64s]                 "decorating a classmethod, be sure to use @method_decorator."
[   64s]             )
[   64s] E           TypeError: never_cache didn't receive an HttpRequest. If you are decorating a classmethod, be sure to use @method_decorator.
[   64s] 
[   64s] /usr/lib/python3.9/site-packages/django/views/decorators/cache.py:52: TypeError
[   64s] ------------------------------ Captured log call -------------------------------
[   64s] ERROR    django.request:log.py:225 Internal Server Error: /grappelli/lookup/related/
[   64s] Traceback (most recent call last):
[   64s]   File "/usr/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
[   64s]     response = get_response(request)
[   64s]   File "/usr/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
[   64s]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[   64s]   File "/usr/lib/python3.9/site-packages/django/views/generic/base.py", line 69, in view
[   64s]     return self.dispatch(request, *args, **kwargs)
[   64s]   File "/usr/lib/python3.9/site-packages/django/views/generic/base.py", line 101, in dispatch
[   64s]     return handler(request, *args, **kwargs)
[   64s]   File "/usr/lib/python3.9/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
[   64s]     raise TypeError(
[   64s] TypeError: never_cache didn't receive an HttpRequest. If you are decorating a classmethod, be sure to use @method_decorator.
[   64s] _________________________ RelatedTests.test_m2m_lookup _________________________
[   64s] 
[   64s] self = <grappelli.tests.test_related.RelatedTests testMethod=test_m2m_lookup>
[   64s] 
[   64s]     def test_m2m_lookup(self):
[   64s]         """
[   64s]         Test M2M lookup
[   64s]         """
[   64s]         self.client.login(username="User001", password="user001")
[   64s] >       response = self.client.get(reverse("grp_related_lookup"))
[   64s] 
[   64s] grappelli/tests/test_related.py:140: 
[   64s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   64s] /usr/lib/python3.9/site-packages/django/test/client.py:747: in get
[   64s]     response = super().get(path, data=data, secure=secure, **extra)
[   64s] /usr/lib/python3.9/site-packages/django/test/client.py:396: in get
[   64s]     return self.generic('GET', path, secure=secure, **{
[   64s] /usr/lib/python3.9/site-packages/django/test/client.py:473: in generic
[   64s]     return self.request(**r)
[   64s] /usr/lib/python3.9/site-packages/django/test/client.py:721: in request
[   64s]     self.check_exception(response)
[   64s] /usr/lib/python3.9/site-packages/django/test/client.py:582: in check_exception
[   64s]     raise exc_value
[   64s] /usr/lib/python3.9/site-packages/django/core/handlers/exception.py:47: in inner
[   64s]     response = get_response(request)
[   64s] /usr/lib/python3.9/site-packages/django/core/handlers/base.py:181: in _get_response
[   64s]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[   64s] /usr/lib/python3.9/site-packages/django/views/generic/base.py:69: in view
[   64s]     return self.dispatch(request, *args, **kwargs)
[   64s] /usr/lib/python3.9/site-packages/django/views/generic/base.py:101: in dispatch
[   64s]     return handler(request, *args, **kwargs)
[   64s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   64s] 
[   64s] request = <grappelli.views.related.RelatedLookup object at 0x7fbbe0afb130>
[   64s] args = (<WSGIRequest: GET '/grappelli/lookup/related/'>,), kwargs = {}
[   64s] 
[   64s]     @wraps(view_func)
[   64s]     def _wrapped_view_func(request, *args, **kwargs):
[   64s]         if not isinstance(request, HttpRequest):
[   64s] >           raise TypeError(
[   64s]                 "never_cache didn't receive an HttpRequest. If you are "
[   64s]                 "decorating a classmethod, be sure to use @method_decorator."
[   64s]             )
[   64s] E           TypeError: never_cache didn't receive an HttpRequest. If you are decorating a classmethod, be sure to use @method_decorator.
[   64s] 
[   64s] /usr/lib/python3.9/site-packages/django/views/decorators/cache.py:52: TypeError
```

**Comment by sehmaschine** [comment]
Thanks. We'll take a look once we work on compatibility with Django 4.

**Comment by JosiahDub** [comment]
The `ifnotequal` template tag has been deprecated in Django 4.0. It's used in `search_form.html`.

**Comment by sehmaschine** [comment]
The plan is to remove Grappelli autocompletes completely (see #981), so it's ok for these tests to fail. I'm still leaving this ticket open for future reference.

**Comment by sehmaschine** [comment]
Decided to keep the Grappelli autocompletes – tests are fine now.
